/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nekomeshi312_stabcam_StabCameraViewFragment */

#ifndef _Included_com_nekomeshi312_stabcam_StabCameraViewFragment
#define _Included_com_nekomeshi312_stabcam_StabCameraViewFragment
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nekomeshi312_stabcam_StabCameraViewFragment_ACTIVIY_REQUEST_CAMERA_SETTING_PREF
#define com_nekomeshi312_stabcam_StabCameraViewFragment_ACTIVIY_REQUEST_CAMERA_SETTING_PREF 0L
/*
 * Class:     com_nekomeshi312_stabcam_StabCameraViewFragment
 * Method:    initStabilize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nekomeshi312_stabcam_StabCameraViewFragment_initStabilize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nekomeshi312_stabcam_StabCameraViewFragment
 * Method:    stopStabilize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nekomeshi312_stabcam_StabCameraViewFragment_stopStabilize
  (JNIEnv *, jobject);

/*
 * Class:     com_nekomeshi312_stabcam_StabCameraViewFragment
 * Method:    getStabilizedImage
 * Signature: ([BJZ)V
 */
JNIEXPORT void JNICALL Java_com_nekomeshi312_stabcam_StabCameraViewFragment_getStabilizedImage
  (JNIEnv *, jobject, jbyteArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
